server:
  port: 8081
spring:
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://127.0.0.1:52362?schema=PRODUCTION&case
    username: SYSDBA
    password: SYSDBA
  data:
    redis:
      host: 192.168.71.101
      port: 6379
      database: 1
